# Generated by Django 4.2.7 on 2024-02-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
