# Generated by Django 5.0 on 2023-12-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_username_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Creative', 'Creative'), ('User', 'User')], max_length=250, null=True),
        ),
    ]
