# Generated by Django 4.2.7 on 2024-02-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_skills_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
