# Generated by Django 4.2.7 on 2024-02-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talentprofile',
            old_name='behance_url',
            new_name='whatsapp_link',
        ),
        migrations.RemoveField(
            model_name='talentprofile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='talentprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='talentprofile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='talentprofile',
            name='linked_in_url',
        ),
        migrations.RemoveField(
            model_name='talentprofile',
            name='medium_url',
        ),
        migrations.RemoveField(
            model_name='talentprofile',
            name='resume_link',
        ),
        migrations.RemoveField(
            model_name='talentprofile',
            name='website_link',
        ),
        migrations.RemoveField(
            model_name='talentprofile',
            name='x_url',
        ),
    ]
