# Generated by Django 4.2.7 on 2024-01-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Client', 'Client'), ('Talent', 'Talent')], max_length=250, null=True),
        ),
    ]
