# Generated by Django 4.2.7 on 2024-02-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_behance_url_talentprofile_whatsapp_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talentprofile',
            old_name='d_skills',
            new_name='skills',
        ),
    ]
