# Generated by Django 4.2.7 on 2024-02-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_d_skills_talentprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='resume_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
