# Generated by Django 4.2.7 on 2024-01-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_about_profile_display_name_profile_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(blank=True, default='profile_pics/', null=True, upload_to='files/images'),
        ),
    ]
