# Generated by Django 4.2.7 on 2024-02-25 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_talentprofile_resume_link_talentprofile_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), default=['hello'], size=None),
            preserve_default=False,
        ),
    ]
