# Generated by Django 4.2.7 on 2024-03-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clientnotification_talentnotification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientnotification',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='talentnotification',
            options={'ordering': ['-date']},
        ),
    ]
