# Generated by Django 4.2.7 on 2024-03-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_clientnotification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='cover_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='files/images'),
        ),
    ]
