# Generated by Django 4.2.7 on 2024-01-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clientprofile_talentprofile_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='current_password',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='new_password',
        ),
    ]
