# Generated by Django 4.2.7 on 2024-04-06 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_talentprofile_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnotification',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientnotification', to='core.clientprofile'),
        ),
    ]
