# Generated by Django 4.2.7 on 2024-01-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_clientprofile_profile_pics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
