# Generated by Django 4.2.7 on 2024-05-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_talentnotification_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
