# Generated by Django 4.2.7 on 2024-01-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_user_profile_pics_clientprofile_profile_pics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='name',
        ),
    ]
