# Generated by Django 4.2.7 on 2024-01-15 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_clientprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('DigitalSkills', 'DigitalSkills'), ('Non-DigitalSkills', 'Non-DigitalSkills')], max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='NonDigitalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, choices=[('Plumber', 'Plumber'), ('Civil-Engineer', 'Civil-Engineer'), ('Catering', 'Catering'), ('Hair_Stylist', 'Hair_stylist'), ('Electronics/Repairs', 'Electronics/Repairs'), ('Upholstery', 'Uphosltery'), ('Cobbling', 'Cobbling'), ('Mechanic', 'Mechanic'), ('Fashion-Designer', 'Fashion-Designer')], max_length=250, null=True)),
                ('talentprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_digitalskills', to='core.talentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, choices=[('BackendDevelopment', 'BackendDevelopment'), ('MobileDevelopment', 'MobileDevelopment'), ('UI/UX_Design', 'UI/UX_Design'), ('Branding_and_Printing', 'Branding_and_Printing'), ('Graphics_Design', 'Graphics_Design'), ('Content_Creation', 'Content_Creation'), ('Frontend_development', 'Frontend_Development')], max_length=250, null=True)),
                ('talentprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_skills', to='core.talentprofile')),
            ],
        ),
    ]
