# Generated by Django 4.2.7 on 2024-06-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_otp_user_otp_secret_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='digital_skills',
            field=models.CharField(blank=True, choices=[('BackendDevelopment', 'BackendDevelopment'), ('MobileDevelopment', 'MobileDevelopment'), ('UI/UX_Design', 'UI/UX_Design'), ('Graphics_Design', 'Graphics_Design'), ('Content_Creation', 'Content_Creation'), ('Frontend_development', 'Frontend_Development')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='nondigital_skills',
            field=models.CharField(blank=True, choices=[('Plumbing', 'Plumbing'), ('Catering', 'Catering'), ('Hair_Stylist', 'Hair_stylist'), ('Electronics/Repairs', 'Electronics/Repairs'), ('Furniture-Making', 'Furniture-Making'), ('Cobbling', 'Cobbling'), ('Mechanic', 'Mechanic'), ('Fashion-Designer', 'Fashion-Designer')], max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name='talentprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.skills'),
        ),
    ]
