# Generated by Django 4.2.7 on 2024-01-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_nondigitalskill_talentprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='digital_skills',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='nondigital_skills',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='digital_skills',
            field=models.CharField(blank=True, choices=[('BackendDevelopment', 'BackendDevelopment'), ('MobileDevelopment', 'MobileDevelopment'), ('UI/UX_Design', 'UI/UX_Design'), ('Branding_and_Printing', 'Branding_and_Printing'), ('Graphics_Design', 'Graphics_Design'), ('Content_Creation', 'Content_Creation'), ('Frontend_development', 'Frontend_Development')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='nondigital_skills',
            field=models.CharField(blank=True, choices=[('Plumber', 'Plumber'), ('Civil-Engineer', 'Civil-Engineer'), ('Catering', 'Catering'), ('Hair_Stylist', 'Hair_stylist'), ('Electronics/Repairs', 'Electronics/Repairs'), ('Upholstery', 'Uphosltery'), ('Cobbling', 'Cobbling'), ('Mechanic', 'Mechanic'), ('Fashion-Designer', 'Fashion-Designer')], max_length=250, null=True),
        ),
    ]
