# Generated by Django 4.2.7 on 2024-06-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_skills_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='images',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery'),
        ),
    ]
