# Generated by Django 4.2.7 on 2024-06-07 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_talentprofile_images_talentprofile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skill'),
        ),
    ]
