# Generated by Django 4.2.7 on 2024-01-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_clientprofile_digital_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='behance_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='linked_in_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='medium_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='resume_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='starting_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='summary_of_profile',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='x_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], max_length=250, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.talentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, choices=[('web-developmant', 'web-development'), ('Javascript', 'Javascript'), ('React', 'React'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Django', 'Django'), ('Flask', 'Flask')], max_length=250, null=True)),
                ('talent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.talentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('talent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.talentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/images')),
                ('talent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.talentprofile')),
            ],
        ),
    ]
