# Generated by Django 4.2.7 on 2024-01-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_talentprofile_behance_url_talentprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
