# Generated by Django 4.2.7 on 2024-01-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='talent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='core.talentprofile'),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='summary_of_profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
