# Generated by Django 4.2.7 on 2024-06-07 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_talentprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skill'),
        ),
    ]
