# Generated by Django 4.2.7 on 2024-01-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_question_alter_gallery_talent_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='talent_profile',
            new_name='profile',
        ),
    ]
