# Generated by Django 4.2.7 on 2024-06-07 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_talentprofile_skills_talentprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='talentprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talentprofile', to='core.talentprofile'),
        ),
    ]
