# Generated by Django 4.2.7 on 2024-06-07 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_talentprofile_skills_skill_talentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='talentprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.talentprofile'),
        ),
    ]
