# Generated by Django 4.2.7 on 2024-01-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_gallery_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.talentprofile'),
        ),
    ]
