# Generated by Django 4.2.7 on 2024-01-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_gallery_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='profile',
            new_name='d_profile',
        ),
    ]
