# Generated by Django 4.2.7 on 2024-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_profile_gallery_d_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='files/images'),
        ),
    ]
