# Generated by Django 4.2.7 on 2024-06-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_skill_talentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
