# Generated by Django 4.2.7 on 2024-01-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_gallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='images',
        ),
    ]
