# Generated by Django 4.2.7 on 2024-06-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_bookedcreative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('DigitalSkills', 'DigitalSkills'), ('Non-DigitalSkills', 'Non-DigitalSkills')], default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='digital_skills',
            field=models.CharField(blank=True, choices=[('BackendDevelopment', 'BackendDevelopment'), ('MobileDevelopment', 'MobileDevelopment'), ('UI/UX_Design', 'UI/UX_Design'), ('Graphics_Design', 'Graphics_Design'), ('Content_Creation', 'Content_Creation'), ('Frontend_development', 'Frontend_Development')], default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='nondigital_skills',
            field=models.CharField(blank=True, choices=[('Plumbing', 'Plumbing'), ('Catering', 'Catering'), ('Hair_Stylist', 'Hair_stylist'), ('Electronics/Repairs', 'Electronics/Repairs'), ('Furniture-Making', 'Furniture-Making'), ('Cobbling', 'Cobbling'), ('Mechanic', 'Mechanic'), ('Fashion-Designer', 'Fashion-Designer')], default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='work_type',
            field=models.CharField(blank=True, choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], default='', max_length=500),
            preserve_default=False,
        ),
    ]
