# Generated by Django 4.2.7 on 2024-01-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_image_gallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='files/images'),
        ),
    ]
