# Generated by Django 4.2.7 on 2024-01-20 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_gallery_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, choices=[('web-developmant', 'web-development'), ('Javascript', 'Javascript'), ('React', 'React'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Django', 'Django'), ('Flask', 'Flask')], max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='skillprofile',
            name='skill',
            field=models.ManyToManyField(to='core.skills'),
        ),
        migrations.AddField(
            model_name='skillprofile',
            name='talent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.talentprofile'),
        ),
    ]
