# Generated by Django 4.2.7 on 2024-01-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_skillprofile_skills_delete_skill_skillprofile_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='talent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.talentprofile'),
        ),
        migrations.DeleteModel(
            name='SkillProfile',
        ),
    ]
