# Generated by Django 4.2.7 on 2024-07-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_talentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcreative',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedcreative',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
