# Generated by Django 4.2.7 on 2024-07-09 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_bookedcreative_description_bookedcreative_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedcreative',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientprofile'),
        ),
        migrations.AlterField(
            model_name='bookedcreative',
            name='talent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.talentprofile'),
        ),
    ]
