# Generated by Django 4.2.7 on 2024-01-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_skills_talent_profile_delete_skillprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(blank=True, choices=[('web-development', 'web-development'), ('Javascript', 'Javascript'), ('React', 'React'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Django', 'Django'), ('Flask', 'Flask')], max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name='skills',
            name='talent_profile',
        ),
        migrations.AddField(
            model_name='skills',
            name='talent_profile',
            field=models.ManyToManyField(blank=True, null=True, related_name='skills', to='core.talentprofile'),
        ),
    ]
