# Generated by Django 4.2.7 on 2024-07-10 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_bookedcreative_client_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedcreative',
            name='talent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='core.talentprofile'),
        ),
    ]
