# Generated by Django 4.2.7 on 2024-01-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_skills_skill_remove_skills_talent_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='talent_profile',
        ),
        migrations.AddField(
            model_name='skills',
            name='talent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.talentprofile'),
        ),
    ]
