# Generated by Django 4.2.7 on 2024-01-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_question_question_question_question1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question1',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question4',
        ),
    ]
