# Generated by Django 4.2.7 on 2024-07-10 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_review_reviewed_alter_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
