# Generated by Django 4.2.7 on 2024-07-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_talentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcreative',
            name='phone_number',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
