# Generated by Django 4.2.7 on 2024-02-21 21:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_workschedule_talent_profile_alter_workschedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='about',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='talent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to='core.talentprofile'),
        ),
    ]
