# Generated by Django 4.2.7 on 2024-07-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_bookedcreative_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedcreative',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='bookedcreative',
            name='phone',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
