# Generated by Django 4.2.7 on 2024-07-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_bookedcreative_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcreative',
            name='talent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.talentprofile'),
        ),
    ]
