# Generated by Django 4.2.7 on 2024-02-21 21:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_talentprofile_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
