# Generated by Django 4.2.7 on 2024-02-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_talentprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
