# Generated by Django 4.2.7 on 2024-07-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_review_image_remove_review_relevant_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='about',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='digital_skills',
            field=models.CharField(blank=True, choices=[('BackendDevelopment', 'BackendDevelopment'), ('MobileDevelopment', 'MobileDevelopment'), ('UI/UX_Design', 'UI/UX_Design'), ('Graphics_Design', 'Graphics_Design'), ('Content_Creation', 'Content_Creation'), ('Frontend_Development', 'Frontend_Development')], max_length=250),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='nondigital_skills',
            field=models.CharField(blank=True, choices=[('Plumbing', 'Plumbing'), ('Catering', 'Catering'), ('Hair_Stylist', 'Hair_Stylist'), ('Electronics/Repairs', 'Electronics/Repairs'), ('Furniture-Making', 'Furniture-Making'), ('Cobbling', 'Cobbling'), ('Mechanic', 'Mechanic'), ('Fashion-Designer', 'Fashion-Designer')], max_length=250),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='website_link',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='whatsapp_link',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
