# Generated by Django 4.2.7 on 2024-07-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_talentprofile_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='cover_image',
            field=models.ImageField(blank=True, default='coverimage.png', null=True, upload_to='files/images'),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='digital_skills',
            field=models.CharField(blank=True, choices=[('BackendDevelopment', 'BackendDevelopment'), ('Photography', 'Photography'), ('Blockchain Developement', 'Blockchain Developement'), ('Video_editing', 'Video_editing'), ('WebsiteDevelopment', 'WebsiteDevelopment'), ('MobileDevelopment', 'MobileDevelopment'), ('UI/UX_Design', 'UI/UX_Design'), ('Graphics_Design', 'Graphics_Design'), ('Content_Creation', 'Content_Creation'), ('Frontend_Development', 'Frontend_Development')], max_length=250),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='nondigital_skills',
            field=models.CharField(blank=True, choices=[('Plumbing', 'Plumbing'), ('Catering', 'Catering'), ('Hair_Stylist', 'Hair_Stylist'), ('Electronics/Repairs', 'Electronics/Repairs'), ('Furniture-Making', 'Furniture-Making'), ('Cobbling', 'Cobbling'), ('Mechanic', 'Mechanic'), ('Cleaning', 'Cleaning'), ('Barbing', 'Barbing'), ('Fashion-Designer', 'Fashion-Designer')], max_length=250),
        ),
    ]
