# Generated by Django 4.2.7 on 2024-08-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_waitlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentprofile',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='profile_pics',
            field=models.ImageField(blank=True, default='newdefault.png', null=True, upload_to='files/images'),
        ),
    ]
