# Generated by Django 4.2.7 on 2024-08-08 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_talentprofile_options_talentprofile_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='files/images')),
                ('talentprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.talentprofile')),
            ],
        ),
    ]
