# Generated by Django 4.2.7 on 2024-08-08 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nin',
            name='talentprofile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.talentprofile'),
        ),
    ]
