# Generated by Django 4.2.7 on 2024-08-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_clientprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
