# Generated by Django 4.2.7 on 2024-08-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_verification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Artisans', 'Artisans')], max_length=250),
        ),
    ]
