# Generated by Django 4.2.7 on 2024-08-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_talentprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='about',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
