# Generated by Django 4.2.7 on 2024-09-10 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_talentprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nin',
            name='talentprofile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nin', to='core.talentprofile'),
        ),
    ]
