# Generated by Django 4.2.7 on 2024-09-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_nin_talentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
