# Generated by Django 4.2.7 on 2024-09-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_talentprofile_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='banned',
        ),
        migrations.AddField(
            model_name='user',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
