# Generated by Django 4.2.7 on 2024-09-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_rename_banned_user_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
