# Generated by Django 4.2.7 on 2024-09-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_user_is_banned_talentprofile_is_banned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talentprofile',
            old_name='location',
            new_name='state',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
