# Generated by Django 4.2.7 on 2024-09-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_rename_nondigital_skills_talentprofile_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='digital_skills',
            field=models.CharField(blank=True, choices=[('BackendDevelopment', 'BackendDevelopment'), ('Photography', 'Photography'), ('Blockchain Developement', 'Blockchain Developement'), ('Video_editing', 'Video_editing'), ('WebsiteDevelopment', 'WebsiteDevelopment'), ('MobileDevelopment', 'MobileDevelopment'), ('UI/UX_Design', 'UI/UX_Design'), ('Graphics_Design', 'Graphics_Design'), ('Content_Creation', 'Content_Creation'), ('Frontend_Development', 'Frontend_Development')], max_length=250),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='starting_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='website_link',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='whatsapp_link',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
