# Generated by Django 4.2.7 on 2024-09-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_talentprofile_digital_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talentprofile',
            old_name='skills',
            new_name='non_digital_skills',
        ),
    ]
