# Generated by Django 4.2.7 on 2024-09-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_rename_non_digital_skills_talentprofile_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
    ]
