# Generated by Django 4.2.7 on 2024-09-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_talentprofile_city_alter_talentprofile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='country',
        ),
    ]
