# Generated by Django 4.2.7 on 2024-09-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_talentprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcreative',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
