# Generated by Django 4.2.7 on 2024-09-16 17:52

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0069_remove_talentprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('charge_id', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Failed', 'Failed')], default='Pending', max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientprofile')),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.talentprofile')),
            ],
        ),
    ]
