# Generated by Django 4.2.7 on 2024-07-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chat_reciever_alter_chat_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
