# Generated by Django 4.2.7 on 2024-07-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
