# Generated by Django 4.2.7 on 2024-09-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_bookedcreative_status'),
        ('wallet', '0004_payment_client_id_payment_talent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='talent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.talentprofile'),
        ),
    ]
