# Generated by Django 4.2.7 on 2024-09-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_payment_client_id_alter_payment_talent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
