# Generated by Django 4.2.7 on 2024-09-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='timestamp',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
