# Generated by Django 4.2.7 on 2024-10-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_rename_earnings_wallet_all_time_earnings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='all_time_earnings',
            new_name='earnings',
        ),
    ]
