# Generated by Django 4.2.7 on 2024-10-06 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_bookedcreative_status'),
        ('wallet', '0009_rename_all_time_earnings_wallet_earnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientprofile')),
                ('talent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.talentprofile')),
            ],
        ),
    ]
