# Generated by Django 4.2.7 on 2024-10-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_solpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='solpayment',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
