# Generated by Django 4.2.7 on 2024-10-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_solpayment_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solpayment',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='solpayment',
            old_name='talent_id',
            new_name='talent',
        ),
    ]
