# Generated by Django 4.2.7 on 2024-10-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_alter_wallet_earnings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='earnings',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
